usermod

diff --git a/docker/root/start-ftp b/docker/root/start-ftp
--- a/docker/root/start-ftp
+++ b/docker/root/start-ftp
@@ -7,11 +7,18 @@ if [ -z $HOST ]; then
   exit 1
 fi
 
+if [ "$FTP_USER" = "root" ]; then
+  echo
+  echo "ERROR: FTP_USER='$FTP_USER' is not valid"
+  echo
+  exit 1
+fi
+
 RESOLVE_HOSTNAME=YES
 
 # if HOST is a dotted quad, then it shouldn't be resolved with DNS
 if [[ $HOST =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+ ]] ; then
-    RESOLVE_HOSTNAME=NO
+  RESOLVE_HOSTNAME=NO
 fi
 
 mkdir -m 0700 -p /var/empty
@@ -22,10 +29,7 @@ existing=$(grep $FTP_USER /etc/passwd | cut -f 1 -d :)
 mkdir -m 0755 -p /data
 
 if [ "$existing" = "$FTP_USER" ] ; then
-  echo
-  echo "ERROR: FTP_USER='$FTP_USER' is not valid"
-  echo
-  exit 1
+  usermod -d /data -s /bin/false -g ftp -p $(openssl passwd $FTP_PASS) $FTP_USER
 else
   useradd -d /data -s /bin/false -g ftp -p $(openssl passwd $FTP_PASS) $FTP_USER
 fi
